### ISSUE TITLE
화면이 너무 작아요

### ISSUE THREAD

**Issue by seojin2923** [sujeb2/sandbox_#4]
![image](https://user-images.githubusercontent.com/76585860/219270385-65da0f81-0ecc-4241-8726-2173149e33cf.png)
:(

**Comment by sujeb2** [comment]
그냥 실행했는데 저렇게 되신건가요, 아니면 해상도를 조절하다가 저렇게 되신건가요

**Comment by seojin2923** [comment]
전 그저 압축을 풀고 실행 했을뿐입니다

**Comment by sujeb2** [comment]
어떻게 재현할수도 없어서 일단 closed로 보류

**Comment by sujeb2** [comment]
해당 버그는 유니티 버전 2021.2미만에서 발생하는걸로 보이며, 현재는 2020.3.11 이므로 다음 업데이트때 2021.2 이상의 버전으로 업데이트 될 예정입니다.
